Repository answerdev/answer, pull requests merged in 2022-10, with the labels that each got.

#19 Update README
  README.md
  README_CN.md
Labels: documentation

#21 Add it_IT translations
  i18n/it_IT.yaml
Labels: documentation, enhancement

#25 feat: add zh_CN translation for frontend
  ui/src/components/Comment/components/Reply/index.tsx
  ui/src/i18n/locales/en.json
  ui/src/i18n/locales/zh_CN.json
  ui/src/pages/Questions/Detail/components/Question/index.tsx
  ui/src/pages/Users/Personal/index.tsx
Labels: enhancement

#48 Refine text content
  CONTRIBUTING.md
  INSTALL.md
  README.md
  ui/src/i18n/locales/en.json
  ui/src/i18n/locales/zh_CN.json
Labels: documentation
